### ISSUE TITLE
Is the recording available on GTC On-Demand?

### ISSUE THREAD

**Issue by hsm207** [dglai/DGL-GTC2019#1]
I couldn't find the recording of this tutorial on [GTC On-Demand](https://on-demand-gtc.gputechconf.com/gtcnew/on-demand-gtc.php).

The recordings should be there since its been more than 30 days since GTC 2019 ended, right?

**Comment by ylfdq1118** [comment]
I believe the tutorial session is different from other talks. It requires that you purchased tutorial/training session pass in order to access it.

I you did purchase that, you need to contact NVIDIA to see what's going wrong.

**Comment by hsm207** [comment]
@ylfdq1118 I did not purchase it. Does this mean I won't be able to to watch the recording?

**Comment by ylfdq1118** [comment]
If you can't find it on NVIDIA website, then I guess no.
